### ISSUE TITLE
Add env options to build script

### ISSUE THREAD

**Issue by rgstephens** [deepset-ai/haystack-demos#2]
Add env options to the build script to make it easier to use the demo with your own data.

| Var                 | Use                                                                             |
| ------------------- | ------------------------------------------------------------------------------- |
| DATA_IMAGE_NAME     | Elastic docker image, default is `deepset/elasticsearch-countries-and-capitals` |
| DATASET_DIR         | Data/Corpus directory, default is `dataset`                                     |
| HAYSTACK_IMAGE_NAME | Haystack build image, default is `deepset/haystack:cpu-main`                    |
| NETWORK             | Docker network name, default is `explore_the_world`                             |

**Comment by julian-risch** [comment]
fixed by PR https://github.com/deepset-ai/haystack-demos/pull/3
