### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by gabazureus** [deepset-ai/haystack-demos#7]
Hello!

First of all, awesome project! Thank you for this demo.

I am trying to use a file that is in Portuguese.

When I run the demo, I get this message:
```"INFO:haystack.modeling.model.language_model:Auto-detected model language: english"```

Is it possible to change the default language of the content in dataset folder and the answers to Portuguese?

If yes, how can I do this? What can I change in the code to achieve this goal?

Thank you!!

**Comment by mayankjobanputra** [comment]
@gabazureus do you have a QA model in Portuguese? if so you can change the model in the pipeline yml and change the dataset according to your need.

**Comment by gabazureus** [comment]
Hello!

I don't have it, do you know where can I find one?

Thanks for the helping!!

**Comment by mayankjobanputra** [comment]
https://huggingface.co/models?pipeline_tag=question-answering&language=pt&sort=downloads

I think here there are some models.

**Comment by gabazureus** [comment]
Thank you!! @mayankjobanputra

**Comment by bilgeyucel** [comment]
This issue seems solved. Do not hesitate to reopen if you have further questions @gabazureus 👍
